### ISSUE TITLE
Negative margins is a bit buggy

### ISSUE THREAD

**Issue by csabaxyz** [actuallyakash/spacers#1]
Awesome little tool.

The only issue I found with it is that sometimes it doesn't seem to handle negative margins well.

When I drag one of the margin handles in the negative direction and let go of the cursor, there are times when the margin won't be draggable anymore. And sometimes when it is draggable, if you drag it even just a little bit, it jumps back to zero.

https://user-images.githubusercontent.com/34774629/125170960-e86f4780-e1b1-11eb-813b-36192feb6c70.mov

**Comment by actuallyakash** [comment]
@csabaxyz thanks for pointing out the issue.

Let me fix this and will update you for sure.

Thanks again.

**Comment by actuallyakash** [comment]
Hey @csabaxyz

This bug has been fixed. Thank you for reporting.
