### ISSUE TITLE
Have this as bookmarklet

### ISSUE THREAD

**Issue by kurtextrem** [actuallyakash/spacers#2]
Having this library as bookmarklet could be useful for devs / UI designers to visually try out different spacings. Maybe something to feature on the website? :)

**Comment by actuallyakash** [comment]
Hey @kurtextrem 

Thanks for the suggestion. I didn't know about bookmarklets.

I tried searching for it but didn't found any website.

Is this a website or a blog?

Sorry, I'm a noob at promoting things. 😅

Let me know. Thanks.

**Comment by kurtextrem** [comment]
Hi @actuallyakash, it's not a way of promoting per se, it's more like making spacers more accessible, as you can use it on any website easier. An example bookmarklet would be: https://github.com/zeman/perfmap. Here's a full list of bookmarklets: https://github.com/lewisje/awesome-bookmarklets
You can drag them into your browser bookmarks, click on it on any website and then it does its magic :)

**Comment by actuallyakash** [comment]
Got it @kurtextrem 

I think bookmarklet doesn't apply on the spacers as this tool is made for no-code tools not to handle or automate some tasks.

Though, I'm still researching how I can implement it through bookmarklet.

Thanks again for the suggestion. :)

**Comment by kurtextrem** [comment]
So I'd have an idea: For every element on the page, make it so that you can change the space after hovering.

**Comment by actuallyakash** [comment]
Hey @kurtextrem 

Thanks for the suggestion and your time. I've added the bookmarklet both in readme and docs.

**Comment by kurtextrem** [comment]
This is great, thank you!
